#!/bin/bash

declare -A resources

CURRENT_THEME_FILE="$HOME/.current_theme"
XRESOURCES_DIR="$HOME/.Xresources.d"
ALACRITTY_DIR="$HOME/.config/alacritty"
NVIM_TEMP_DIR="/tmp/nvim"

current_theme=$(cat "$CURRENT_THEME_FILE" 2> /dev/null)

if [[ "$current_theme" == "dark" ]]; then
    echo "light" > "$CURRENT_THEME_FILE"
    cat "$XRESOURCES_DIR/light" > "$XRESOURCES_DIR/colors"
else
    echo "dark" > "$CURRENT_THEME_FILE"
    cat "$XRESOURCES_DIR/dark" > "$XRESOURCES_DIR/colors"
fi

xrdb -load "$HOME/.Xresources"

while read -r line; do
    key=$(echo "$line" | cut -d ":" -f 1)
    val=$(echo "$line" | cut -f 2 | sed "s/#//")
    resources[$key]=$val
done < <(xrdb -query -all)

cat << _EOF_ > "$ALACRITTY_DIR/colors.toml"
[colors.primary]
background = "0x${resources["*background"]}"
foreground = "0x${resources["*foreground"]}"

[colors.cursor]
text = "0x${resources["*text"]}"
cursor = "0x${resources["*cursor"]}"

[colors.normal]
black = "0x${resources["*color0"]}"
red = "0x${resources["*color1"]}"
green = "0x${resources["*color2"]}"
yellow = "0x${resources["*color3"]}"
blue = "0x${resources["*color4"]}"
magenta = "0x${resources["*color5"]}"
cyan = "0x${resources["*color6"]}"
white = "0x${resources["*color7"]}"

[colors.bright]
black = "0x${resources["*color10"]}"
red = "0x${resources["*color11"]}"
green = "0x${resources["*color12"]}"
yellow = "0x${resources["*color13"]}"
blue = "0x${resources["*color14"]}"
magenta = "0x${resources["*color15"]}"
cyan = "0x${resources["*color16"]}"
white = "0x${resources["*color17"]}"

[[colors.indexed_colors]]
index = 16
color = "0x${resources["*color16"]}"

[[colors.indexed_colors]]
index = 17
color = "0x${resources["*color17"]}"

[[colors.indexed_colors]]
index = 18
color = "0x${resources["*color18"]}"

[[colors.indexed_colors]]
index = 19
color = "0x${resources["*color19"]}"

[[colors.indexed_colors]]
index = 20
color = "0x${resources["*color20"]}"

[[colors.indexed_colors]]
index = 21
color = "0x${resources["*color21"]}"
_EOF_

touch "$ALACRITTY_DIR/alacritty.toml"
i3-msg -q restart

for socket in "$NVIM_TEMP_DIR"/*; do
    nvim --server "$socket" --remote-send ":UpdateColorScheme<cr>"
done
